### ISSUE TITLE
Unable to build TES3Edit or TES3Dump

### ISSUE THREAD

**Issue by aperfilev** [TES5Edit/TES3Edit#1]
I try to build this project (with Delphi 10.1 Berlin) from scratch but I get errors with unresolved dependencies
units:
madExcept,
JvCheckListBox,
JvComboBox,
Imaging,
ImagingTypes

Can somebody simply upload current binaries TES3Edit.exe, TES3Dump.exe please?
That would simplify all - I simply want to evaluate this tools.

**Comment by zilav** [comment]
Those tools don't exist. xEdit supports only Oblivion and later games.
